apiVersion: v1
kind: ServiceAccount
metadata:
  name: console
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: console
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: console
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: console
type: kubernetes.io/service-account-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: kube-system
  labels:
    app: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
      - name: console-app
        # OCP K8s version map (https://gist.github.com/jeyaramashok/ebbd25f36338de4422fd584fea841c08)
        # Image (https://quay.io/repository/openshift/origin-console?tab=tags)     
        image: quay.io/openshift/origin-console:4.18
        env:
        - name: BRIDGE_USER_AUTH
          value: disabled # no authentication required
        - name: BRIDGE_K8S_MODE
          value: off-cluster
        - name: BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT
          value: https://kubernetes.default #master api
        - name: BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS
          value: "true" # no tls enabled
        - name: BRIDGE_K8S_AUTH
          value: bearer-token
        - name: BRIDGE_K8S_AUTH_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: console
              key: token
---
kind: Service
apiVersion: v1
metadata:
  name: console
  namespace: kube-system
spec:
  selector:
    app: console
  type: NodePort 
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    nodePort: 30090
    protocol: TCP
