apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd-apps
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: test-apps
    repoURL: 'https://github.com/cloudcafetech/k8sdemo'
    targetRevision: HEAD
    directory:
      exclude: '{minio-appset.yaml,addon-appset.yaml}'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
