apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgdb-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pgdb-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pgdb-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pgdb-role
subjects:
  - kind: ServiceAccount
    name: pgdb-sa
    #namespace: 
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pg-db-setup
spec:
  template:
    spec:
      containers:
        #- image: registry.redhat.io/openshift4/ose-cli
        - image: bitnami/kubectl
          command:
            - /bin/bash
            - -c
            - |
              sleep 20
              POD=$(kubectl get po | grep instance1 | awk '{ print $1 }')
              kubectl exec $POD -- psql -c "CREATE USER confuser PASSWORD 'confpass';"
              kubectl exec $POD -- psql -c "CREATE SCHEMA conf_db;"
              kubectl exec $POD -- psql -c "GRANT USAGE ON SCHEMA conf_db TO confuser ;"
              kubectl exec $POD -- psql -c "GRANT CREATE ON SCHEMA conf_db TO confuser ;"
              kubectl exec $POD -- psql -c "GRANT ALL ON SCHEMA conf_db TO confuser ;"
              kubectl exec $POD -- psql -c "GRANT ALL ON ALL TABLES IN SCHEMA conf_db TO confuser ;"
              kubectl exec $POD -- psql -c "CREATE DATABASE conf_db WITH ENCODING 'UTF-8' OWNER confuser LC_COLLATE = 'en_US.UTF-8' TEMPLATE template0 ;"
              kubectl exec $POD -- psql -c "GRANT CONNECT ON DATABASE conf_db TO confuser ;"
          imagePullPolicy: Always
          name: pg-db-setup 
          env:
            - name: DB_NAME
              value: "conf_db"
          env:
            - name: DB_USER
              value: "confuser"
          env:
            - name: DB_PASS
              value: "confpass"
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      serviceAccountName: pgdb-sa
