apiVersion: v1
kind: ServiceAccount
metadata:
  name: pg-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pg-client
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pg-client
roleRef:
  kind: Role
  name: pg-client
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: pg-client
---
apiVersion: v1
kind: Pod
metadata:
  name: pg-client
  labels:
    app: pg-client 
spec:
  serviceAccountName: pg-client
  securityContext:
    runAsNonRoot: true
    supplementalGroups: [ 10001] 
    fsGroup: 10001    
  containers:
    - name: pg-client
      image: andreswebs/postgresql-client
      imagePullPolicy: Always
      securityContext:
        runAsUser: 1000      
      stdin: true
      tty: true
      command: ["/bin/sh"]
      # conncet command : psql -h <K8S-SVC> -U <USER> --password -p <DBNAME>
