apiVersion: argoproj.io/v1alpha1 
kind: ApplicationSet
metadata:
  name: minio
  namespace: argocd
spec:
  generators:
  - list: 
      elements: 
      - cluster: snd
        url: https://172.30.1.2:19091
      - cluster: mgm
        url: https://kubernetes.default.svc
  template: 
    metadata:
      name: '{{cluster}}-minio'
    spec:
      source:
        repoURL: https://github.com/cloudcafetech/k8sdemo
        targetRevision: HEAD
        path: minio/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: minio
      project: default
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
