cert-manager:
  installCRDs: false
  replicaCount: 1
  image:
    repository: 172.30.1.2:5000/jetstack/cert-manager-controller:v1.13.3
    pullPolicy: IfNotPresent

  webhook:
    image:
      repository: 172.30.1.2:5000/jetstack/cert-manager-webhook:v1.13.3
  cainjector:
    image:
      repository: 172.30.1.2:5000/jetstack/cert-manager-cainjector:v1.13.3
  acmesolver:
    image:
      repository: 172.30.1.2:5000/jetstack/cert-manager-acmesolver:v1.13.3
  startupapicheck:
    image:
      repository: 172.30.1.2:5000/jetstack/cert-manager-ctl:v1.13.3
