cert-manager:
  installCRDs: true
  replicaCount: 1
  image:
    repository: 172.30.1.2:5000/jetstack/cert-manager-controller
    pullPolicy: IfNotPresent

  webhook:
    image:
      repository: 172.30.1.2:5000/jetstack/cert-manager-webhook
  cainjector:
    image:
      repository: 172.30.1.2:5000/jetstack/cert-manager-cainjector
  acmesolver:
    image:
      repository: 172.30.1.2:5000/jetstack/cert-manager-acmesolver
  startupapicheck:
    image:
      repository: 172.30.1.2:5000/jetstack/cert-manager-ctl
